plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace "com.lumi.app"
    compileSdk 34

    defaultConfig {
        applicationId "com.lumi.app"
        minSdk 23
        targetSdk 34
        versionCode 1
        versionName "3.1"
    }

    signingConfigs {
        lumi {
            storeFile file("lumi-debug.keystore")
            storePassword "lumi12345"
            keyAlias "lumikey"
            keyPassword "lumi12345"
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.lumi
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.lumi
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    buildFeatures {
        viewBinding true
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.webkit:webkit:1.11.0'
}
